using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Magneto.Desktop.WinUI.Core.Models.Motors;
using Magneto.Desktop.WinUI.Core.Models.Print;
using static Magneto.Desktop.WinUI.Core.Models.Constants.MagnetoConstants;
using static Magneto.Desktop.WinUI.Core.Models.Print.CommandQueueManager;

namespace Magneto.Desktop.WinUI.Core.Contracts.Services;
public interface IMotorService
{
    void Initialize();
    void HandleStartUp();
    public CommandQueueManager GetCommandQueueManager();
    public Task ReadBuildMotorErrors();
    public Task ReadPowderMotorErrors();
    public Task ReadSweepMotorErrors();
    public Task ReadAndClearAllErrors();
    public string[] WriteAbsoluteMoveProgramForBuildMotor(double target, bool moveUp);
    public string[] WriteAbsoluteMoveProgramForPowderMotor(double target, bool moveUp);
    public string[] WriteAbsoluteMoveProgramForSweepMotor(double target, bool moveUp);
    public string[] WriteRelativeMoveProgramForBuildMotor(double steps, bool moveUp);
    public string[] WriteRelativeMoveProgramForPowderMotor(double steps, bool moveUp);
    public string[] WriteRelativeMoveProgramForSweepMotor(double steps, bool moveUp);
    public void SendProgram(string motorNameLower, string[] program);
    public Task<bool> IsProgramRunningAsync(string motorNameLower);
    public void AddProgramFront(string[] program, Controller controller, int axis);
    public void AddProgramFront(string motorNameLower, string[] program);
    public void AddProgramLast(string[] program, Controller controller, int axis);
    public void AddProgramLast(string motorNameLower, string[] program);
    public int GetNumberOfPrograms();
    public ProgramNode? GetFirstProgramNode();
    public ProgramNode? GetLastProgramNode();
    public void StopMotor(string motorNameLower);
    public void StopAllMotors();
    public bool IsProgramPaused();
    public void PauseProgram();
    public Task ExecuteLayerMove(double thickness, double amplifier, int numberOfLayers);
    public (string[] program, Controller controller, int axis)? ExtractProgramNodeVariables(ProgramNode programNode);
    public int GetMotorAxis(string motorName);
    double GetMaxSweepPosition();
    public Task<double> GetMotorPositionAsync(string motorNameLowerCase);
    Task<double> GetBuildMotorPositionAsync();
    Task<double> GetPowderMotorPositionAsync();
    Task<double> GetSweepMotorPositionAsync();
    Task<(int res, double position)> HandleGetPositionAsync(string motorNameLowerCase);
    void ConfigurePortEventHandlers();
    void IntializeMotors();
    void HandleMotorInit(string motorNameLowerCase, StepperMotor motor, out StepperMotor motorField);
    void InitializeMotorMap();
    Task<int> MoveMotorAbs(string motorNameLowerCase, double target);
    Task<int> MoveBuildMotorAbs(double target);
    Task<int> MovePowderMotorAbs(double target);
    Task<int> MoveSweepMotorAbs(double target);
    Task<int> MoveMotorRel(string motorNameLowerCase, double distance);
    Task<int> MoveBuildMotorRel(double distance);
    Task<int> MovePowderMotorRel(double distance);
    Task<int> MoveSweepMotorRel(double distance);
    bool MotorsRunning();
    bool CheckMotorStopFlag(string motorNameLowerCase);
    void EnableBuildMotor();
    void EnablePowderMotor();
    void EnableSweepMotor();
    void EnableMotors();
    Task<int> StopMotorAndClearQueue(string motorNameLowerCase);
    Task<int> HomeMotor(StepperMotor motor);
    Task<int> HomeMotor(string motorNameLowerCase);
    Task<int> WaitUntilMotorHomedAsync(string motorNameLowerCase);
    Task<int> WaitUntilBuildReachesTargetAsync(double targetPos);
    Task<int> WaitUntilPowderReachesTargetAsync(double targetPos);
    Task<int> WaitUntilSweepReachesTargetAsync(double targetPos);
}
