using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Magneto.Desktop.WinUI.Core.Models.Motors;
using Magneto.Desktop.WinUI.Core.Models.Print;

namespace Magneto.Desktop.WinUI.Core.Contracts.Services;
public interface IMotorService
{
    void Initialize();
    void HandleStartUp();
    public CommandQueueManager GetActuationManager();
    StepperMotor GetBuildMotor();
    StepperMotor GetPowderMotor();
    StepperMotor GetSweepMotor();
    double GetMaxSweepPosition();
    public Task<double> GetMotorPositionAsync(StepperMotor motor);
    public Task<double> GetMotorPositionAsync(string motorNameLowerCase);
    Task<double> GetBuildMotorPositionAsync();
    Task<double> GetPowderMotorPositionAsync();
    Task<double> GetSweepMotorPositionAsync();
    void ConfigurePortEventHandlers();
    void IntializeMotors();
    void HandleMotorInit(string motorNameLowerCase, StepperMotor motor, out StepperMotor motorField);
    void InitializeMotorMap();
    Task<int> MoveBuildMotor(bool moveAbs, double value);
    Task<int> MovePowderMotor(bool moveAbs, double value);
    Task<int> MoveSweepMotor(bool moveAbs, double value);
    Task<int> MoveMotorAbs(string motorNameLowerCase, double target);
    Task<int> MoveBuildMotorAbs(double target);
    Task<int> MovePowderMotorAbs(double target);
    Task<int> MoveSweepMotorAbs(double target);
    Task<int> MoveMotorRel(StepperMotor motor, double distance);
    Task<int> MoveMotorRel(string motorNameLowerCase, double distance);
    Task<int> MoveBuildMotorRel(double distance);
    Task<int> MovePowderMotorRel(double distance);
    Task<int> MoveSweepMotorRel(double distance);
    Task<int> LayerMove(double layerThickness, double supplyAmplifier);
    bool MotorsRunning();
    bool CheckMotorStopFlag(string motorNameLowerCase);
    void EnableBuildMotor();
    void EnablePowderMotor();
    void EnableSweepMotor();
    void EnableMotors();
    Task<int> StopMotorAndClearQueue(StepperMotor motor);
    Task<int> StopMotorAndClearQueue(string motorNameLowerCase);
    Task<int> HomeMotor(StepperMotor motor);
    Task<int> HomeMotor(string motorNameLowerCase);
    Task<int> WaitUntilMotorHomedAsync(string motorNameLowerCase);
    //Task<int> WaitUntilAtTargetAsync(StepperMotor motor, double targetPos);
    Task<int> WaitUntilBuildReachesTargetAsync(double targetPos);
    Task<int> WaitUntilPowderReachesTargetAsync(double targetPos);
    Task<int> WaitUntilSweepReachesTargetAsync(double targetPos);
}
